### ISSUE TITLE
To-Do List For Flat

### ISSUE THREAD

**Issue by chiqors** [chiqors/FlatOPG#2]
# List of task From V1.4

## Task Improvement
- [x] Improve bottom.php & Flat.js.
- [ ] Add more icons for any pages, buttons, titles.
- [ ] Add more flat images.
- [ ] Reshape containers to be more square sharpness.
- [ ] Improve & Add Hover in need to make beautiful panel site.
- [ ] Improve Input with Flat style (button, input, combobox, etc).
And more in under investigation..

-----------------------

## Task Fixing
- [x] Watch logger's Collapsing (not showing).
- [x] Sidebar overview position (wrong position).
And more in under investigation..

Report anything suggestion & bugs that you want to add to our task on comment below.

**Comment by Carlosdurango** [comment]
Muy buena
